// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Gere este arquivo de verdade com:
/// `flutterfire configure --project=financas-wellysson --platforms=android,web --yes`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'run flutterfire configure.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'run flutterfire configure.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run flutterfire configure.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Substitua rodando `flutterfire configure --project=financas-wellysson`

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCiXN1LzU_Sb7jjDJfjZibF-wBmUnGLwY',
    appId: '1:938876943322:web:e4602423a75ffb7a8bdee3',
    messagingSenderId: '938876943322',
    projectId: 'financas-wellysson',
    authDomain: 'financas-wellysson.firebaseapp.com',
    storageBucket: 'financas-wellysson.firebasestorage.app',
    measurementId: 'G-HBSGBQN4RT',
  );
  /// Substitua rodando `flutterfire configure --project=financas-wellysson`

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAUGg3c99v0qIrbYLFsbgKADca_Qpv9lM',
    appId: '1:938876943322:android:b3117aa6317edb338bdee3',
    messagingSenderId: '938876943322',
    projectId: 'financas-wellysson',
    storageBucket: 'financas-wellysson.firebasestorage.app',
  );
}
